using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SC_AmbianceManager : MonoBehaviour
{
    [SerializeField]
    GameObject source;
    GameObject checkList;
    string ambianceName;

    bool ambianceplayed;
    enum player
    {
        pilote,
        operateur,
        menu
    }

    [SerializeField]
    player Player;
    
    // Start is called before the first frame update
    void Start()
    {
        ambianceName = null;
        ambianceplayed = false;
        switch (Player)
        {
            case player.pilote:
                ambianceName = "SFX_p_ambiance";
                GetReference();
                break;


            case player.operateur:
                ambianceName = "SFX_o_ambiance";
                break;

            case player.menu:
                ambianceName = "SFX_p_ambiance";
                StartCockpitAmbiance();
                break;
        }
       
    }

    void Update()
    {
        if(!ambianceplayed)
        GetReference();
    }


    void GetReference()
    {

        if (checkList == null)
            checkList = GameObject.FindGameObjectWithTag("Mng_CheckList");
        else
            StartCockpitAmbiance();
    }

    public void StartCockpitAmbiance()
    {
        CustomSoundManager.Instance.PlaySound(source, ambianceName, true, 0.4f);
        ambianceplayed = true;
    }
}
